### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by dy** [distributions-io/distributions.io#1]
Hello!
Please publish this (awesome) package to npm. Thank you for the great job!

**Comment by Planeshifter** [comment]
It will land on npm eventually, hopefully rather sooner than later. There are still things to do, though, e.g. some sub-modules still need to be written and documentation has to be created. For now, you could either install the individual modules or install this package via npm directly from GitHub, e.g. by typing 

```
npm install https://github.com/distributions-io/distributions.io.git
```

Any specific modules you need to have access to right now? I will continue to publish modules to npm in the coming weeks. 
Thank you for your interest in the package!

**Comment by Planeshifter** [comment]
I uploaded a preliminary version of the package, in which many functions are still missing, to npm, so I will close this issue now. Thanks again for your interest in `distributions-io`.

**Comment by dy** [comment]
cool, thanks
