### ISSUE TITLE
Converting tabulated data to distribution params

### ISSUE THREAD

**Issue by tourman** [distributions-io/distributions.io#2]
Assume I have the data in the spreadsheet. I want to understand the law it distributes itself and the params for the distribution function.

* **In**: tabulated data
* **Out**: set of distribution params (mean, standard deviation, lambda for exp-based distribution, etc.)

**Comment by kgryte** [comment]
@tourman You may want to consult https://github.com/stdlib-js/stdlib which is the more recent iteration of this project. Feel free to file an issue there. Thanks!
